[phases.setup]
nixPkgs = ['php82', 'nodejs', 'npm', 'composer', 'libpng', 'libjpeg', 'freetype', 'zlib', 'libzip']

[phases.build]
cmds = [
    'install-php-extensions gd zip bcmath intl pdo_mysql',
    'composer install --optimize-autoloader --no-scripts --no-interaction',
    'npm install',
    'npm run build'
]

[phases.deploy]
cmds = [
    'php artisan migrate --force',
    'php artisan optimize',
    'php artisan serve --host 0.0.0.0 --port $PORT'
]
