# Project metadata
sonar.projectKey=LogiSaaS-Courier-System
sonar.projectName=LogiSaaS
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=app, resources/views, routes, database

# Language and encoding
sonar.language=php
sonar.sourceEncoding=UTF-8

# Exclusions (Files that shouldn't be analyzed for quality)
sonar.exclusions=vendor/**, public/**, storage/**, tests/**, node_modules/**, database/migrations/**

# Test and Coverage (If you have PHPUnit setup)
sonar.tests=tests
sonar.php.tests.reportPath=storage/logs/tests-report.xml
sonar.php.coverage.reportPaths=storage/logs/clover.xml

# Quality Gates specific for Laravel
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S1135
sonar.issue.ignore.multicriteria.e1.resourceKey=app/Notifications/*
