/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d5e3fc",
        "on-tertiary-container": "#d95f00",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffdbca",
        "on-surface": "#0d1c2e",
        "on-secondary-fixed": "#00174b",
        "outline-variant": "#c6c6cd",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#3f465c",
        "on-primary-fixed": "#131b2e",
        "primary-fixed-dim": "#bec6e0",
        "surface-dim": "#ccdbf3",
        "secondary-container": "#316bf3",
        "surface-tint": "#565e74",
        "on-tertiary-fixed": "#341100",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#45464d",
        "on-secondary": "#ffffff",
        "surface-base": "#FFFFFF",
        "on-secondary-fixed-variant": "#003ea8",
        "data-teal": "#0D9488",
        "on-background": "#0d1c2e",
        "primary": "#000000",
        "on-tertiary": "#ffffff",
        "primary-container": "#131b2e",
        "tertiary": "#000000",
        "on-primary-container": "#7c839b",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "inverse-primary": "#bec6e0",
        "surface": "#f8f9ff",
        "secondary": "#0051d5",
        "primary-fixed": "#dae2fd",
        "border-light": "#E2E8F0",
        "inverse-surface": "#233144",
        "outline": "#76777d",
        "surface-variant": "#d5e3fc",
        "tertiary-fixed-dim": "#ffb690",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#783200",
        "background": "#f8f9ff",
        "surface-subtle": "#F8FAFC",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "tertiary-container": "#341100",
        "error": "#ba1a1a",
        "cta-orange": "#F97316"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "base": "8px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "stack-lg": "48px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "title-lg": ["Inter"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Inter"]
      },
      fontSize: {
        'headline-lg': ['3.5rem', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-md': ['2.5rem', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-sm': ['1.5rem', { lineHeight: '1.2', fontWeight: '700' }],
        'title-lg': ['1.25rem', { lineHeight: '1.5', fontWeight: '600' }],
        'label-md': ['0.875rem', { lineHeight: '1.25', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1rem', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.25', fontWeight: '400' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'pulse-slow': 'pulse 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        }
      }
    },
  },
  plugins: [],
}
